SECTION 2: VIDEO 19

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


VIDEO 20


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7,8] ,
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
#Tensors

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random tensors

In [ ]:
# create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.5239, 0.9371, 0.2712, 0.4266],
        [0.5656, 0.4849, 0.3497, 0.1591],
        [0.6472, 0.1630, 0.5657, 0.3411]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create an random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3)) # h,w,color channels (R, G, B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
# use torch.range()

one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  #what dtype is tensor(e.g float32 or float 16)
                               device=None,  #what device is your tensor one
                               requires_grad=False)   # whether or not to track gradients wirth this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
## getting information from tensors

# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.2301, 0.8342, 0.0522, 0.9252],
        [0.5318, 0.8750, 0.6820, 0.3995],
        [0.8788, 0.8618, 0.3023, 0.3132]])

In [ ]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2301, 0.8342, 0.0522, 0.9252],
        [0.5318, 0.8750, 0.6820, 0.3995],
        [0.8788, 0.8618, 0.3023, 0.3132]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

In [ ]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10

tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
#substract 10

tensor - 10

tensor([ 0, 10, 20])

In [ ]:
# pytorch inbuilt functions

torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,2)

tensor([12, 22, 32])

### matrix multiplication

In [ ]:
# element wise multiplication

# matrix mul (dot product)

In [ ]:
#element wise multiplication

tensor = torch.tensor([1,2,3])

print(tensor, "*" , tensor)

print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#matrix mul by hand

1*1 + 2*2 + 3*3

14

In [ ]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 3.06 ms, sys: 16 µs, total: 3.08 ms
Wall time: 2.97 ms


In [ ]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 78 µs, sys: 13 µs, total: 91 µs
Wall time: 95.1 µs


tensor(14)

#One of the most common errors in deepl learning(shape errors)

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
# the inner dimesions must match
# the resulting matrix has the shape of the outer dimesions

torch.matmul(torch.rand(2,3) , torch.rand(3,2))

tensor([[0.8257, 0.6081],
        [1.6378, 1.0337]])

In [ ]:
torch.matmul(torch.rand(3,3) , torch.rand(3,3))

tensor([[0.8351, 0.4018, 0.6010],
        [1.5118, 0.7661, 0.4043],
        [1.0833, 0.5066, 0.6381]])

In [ ]:
torch.matmul(torch.rand(3,10) , torch.rand(10,3))

tensor([[2.4076, 2.1417, 1.9663],
        [2.9156, 2.8403, 2.2742],
        [2.1226, 1.8972, 1.6420]])

In [ ]:
torch.matmul(torch.rand(10,2) , torch.rand(2,10)).shape

torch.Size([10, 10])

In [ ]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


torch.matmul(tensor_A, tensor_B)

# torch.mm(tensor_A, tensor_B) is same

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# to fix tensor shape issues , we can manipulate the shape of one of our tensors using a transpose.
# it switches the axes or dimensions of given tensor





In [ ]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B , tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum etc(tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.dtype

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[0]

#value at position 0 is 1

tensor(0)

In [ ]:
x[9]

tensor(90)

## Reshaping, Stacking, Squeezing and Unsqueezing Tensors

In [ ]:
x = torch.arange(1., 10.)

x ,  x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension

x_reshaped = x.reshape(1, 9)

x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#add an extra dimension

x_reshaped = x.reshape(9, 1)

x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x = torch.arange(1., 11.)

x ,  x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
#add an extra dimension

x_reshaped = x.reshape(5, 2)

x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x = torch.arange(1., 10.)

x ,  x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension

x_reshaped = x.reshape(1, 9)

x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# chnage the view


z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change view (keeps same data as original but changes view)

z[:, 0] = 5

z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)

x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=1)

x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous target: {x_squeezed}")
print(f"Previous shape:  {x_squeezed.shape}")

#add an extra dimesion with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:  torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new shape: torch.Size([9, 1])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous target: {x_squeezed}")
print(f"Previous shape:  {x_squeezed.shape}")

#add an extra dimesion with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:  torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [ ]:
# rearrange the dim of target tensor in specified order

x_original = torch.rand(size=(224, 224, 3)) # [h,w,color_channel]

#permute the original tensor to a=rearrange the axis (or dim) order

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")

print(f"New shape: {x_permuted.shape}") #color_channe;,h,w

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

###same as indexing in numpy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# index on new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets index on middle bracket(dim=1)

x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2]

tensor([7, 8, 9])

In [ ]:
# index on most inner bracket (last dim)

x[0][0][0]

tensor(1)

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# use : to select all of a target dim

x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, 1]

tensor([[4, 5, 6]])

In [ ]:
x[:, 2]

tensor([[7, 8, 9]])

In [ ]:
# get all vales of 0th and 1st dim but only index 1 od 2nd dim

x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all vales of 0th dim but only the 1 index value of 1st and 2nd dim

x[:, 1, 1]

tensor([5])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# get index 0 of 0th and 1st dim and all values of 2nd dim

x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9

print(x[0][2][2])

# index on x to return 3,6,9

print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Pytorch Tensors and Numpy

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

### Reproducibility (trying yo take random out of random)

In [ ]:
import torch
import numpy as np

In [ ]:
torch.rand(3,3)

tensor([[0.5606, 0.7318, 0.9693],
        [0.6590, 0.5344, 0.9898],
        [0.6290, 0.3807, 0.3913]])

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)



tensor([[0.9449, 0.6686, 0.7573, 0.8944],
        [0.4916, 0.7914, 0.0127, 0.2463],
        [0.7718, 0.0913, 0.4264, 0.4536]])
tensor([[0.6820, 0.9233, 0.0550, 0.4067],
        [0.1040, 0.5329, 0.3420, 0.8427],
        [0.8877, 0.7930, 0.2465, 0.3231]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch objects on the GPUs(and making faster computations)


In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cpu'

In [ ]:
torch.cuda.device_count()

0

### Putting tensors (and models) on the GPU

In [ ]:
tensor = torch.tensor([1, 2, 3], device = "cpu")

#tensor not on gpu

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:


# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])

### Exercise

In [ ]:
import torch

In [ ]:
tensor1 = torch.rand(7,7)
tensor1.shape

torch.Size([7, 7])

In [ ]:
tensor2 = torch.rand(1,7)
tensor2.shape

torch.Size([1, 7])

In [ ]:
tensor1

tensor([[0.6834, 0.6949, 0.3196, 0.1956, 0.0223, 0.6847, 0.3319],
        [0.4160, 0.2590, 0.9174, 0.2271, 0.3370, 0.1553, 0.5693],
        [0.9090, 0.8761, 0.5282, 0.5656, 0.3975, 0.2372, 0.2930],
        [0.0711, 0.2573, 0.3251, 0.6382, 0.9227, 0.9994, 0.2339],
        [0.2001, 0.6586, 0.5832, 0.5649, 0.2181, 0.7045, 0.9494],
        [0.9736, 0.5475, 0.9044, 0.0551, 0.4042, 0.8074, 0.4892],
        [0.4113, 0.8953, 0.9542, 0.9237, 0.3607, 0.4992, 0.8771]])

In [ ]:
tensor2

tensor([[0.8165, 0.5370, 0.7162, 0.5469, 0.3278, 0.8304, 0.8706]])

In [ ]:
tensor1*tensor2

tensor([[0.5580, 0.3732, 0.2289, 0.1070, 0.0073, 0.5685, 0.2889],
        [0.3396, 0.1391, 0.6571, 0.1242, 0.1105, 0.1289, 0.4956],
        [0.7422, 0.4705, 0.3783, 0.3093, 0.1303, 0.1970, 0.2551],
        [0.0580, 0.1382, 0.2328, 0.3490, 0.3024, 0.8299, 0.2036],
        [0.1634, 0.3537, 0.4177, 0.3089, 0.0715, 0.5850, 0.8265],
        [0.7949, 0.2940, 0.6478, 0.0301, 0.1325, 0.6704, 0.4259],
        [0.3358, 0.4808, 0.6834, 0.5052, 0.1182, 0.4145, 0.7636]])

In [ ]:
torch.matmul(tensor1, tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7)