SECTION 2: VIDEO 19

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


VIDEO 20


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7,8] ,
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
#Tensors

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random tensors

In [ ]:
# create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.5239, 0.9371, 0.2712, 0.4266],
        [0.5656, 0.4849, 0.3497, 0.1591],
        [0.6472, 0.1630, 0.5657, 0.3411]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# create an random tensor with similar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3)) # h,w,color channels (R, G, B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
# use torch.range()

one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  #what dtype is tensor(e.g float32 or float 16)
                               device=None,  #what device is your tensor one
                               requires_grad=False)   # whether or not to track gradients wirth this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
## getting information from tensors

# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.2301, 0.8342, 0.0522, 0.9252],
        [0.5318, 0.8750, 0.6820, 0.3995],
        [0.8788, 0.8618, 0.3023, 0.3132]])

In [ ]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2301, 0.8342, 0.0522, 0.9252],
        [0.5318, 0.8750, 0.6820, 0.3995],
        [0.8788, 0.8618, 0.3023, 0.3132]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

In [ ]:
# create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10

tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
#substract 10

tensor - 10

tensor([ 0, 10, 20])

In [ ]:
# pytorch inbuilt functions

torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,2)

tensor([12, 22, 32])