In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.6.0+cu124


# Introduction to Tensors
## Creating tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#dimension of scalar , dimension is no of square brackets(pairs)
scalar.ndim

0

In [ ]:
# get tensor back as python int

scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# in pytorch everytime yu encode data into numbers its of a tensor data type
# MATRIX


MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# 1 3 by 3 shape matrix
# the 0th dim

TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Random tensors are important because the way may neural network learn is that they strt with tesnors full of random nukbers and then adjust numbers to better represent the data.

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
# create a random tensorof size or shape (3,4)

random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.5678, 0.0334, 0.3390, 0.1114],
        [0.7440, 0.5749, 0.6173, 0.0173],
        [0.3593, 0.1276, 0.5527, 0.6965]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor = torch.rand(1, 3, 4)

random_tensor

tensor([[[0.8360, 0.5435, 0.3839, 0.2831],
         [0.0946, 0.4024, 0.1289, 0.0758],
         [0.3926, 0.1841, 0.8765, 0.2073]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)